### ISSUE TITLE
Measuring tool not functioning

### ISSUE THREAD

**Issue by odelphia** [kartena/Leaflet.EditableHandlers#10]
Does this work with mapbox layers or do I need to create a marker layer?
Can you see what is missing from my page?
http://erichsen-group.com/demoland/taylorpeterh/

C

**Comment by keyjote** [comment]
Hi, first of all, I don't know how to active the measuring tool in your site and looking at the code behind it seems as that library is not there, is it there?
I have not tested with mapbox. could you point out what the problem you get is!

**Comment by keyjote** [comment]
Hi odelphia

Sorry the delay, I had a sick daughter for a few days.

The link you mention here does not exist, I get an error page when it is
being loaded  (Error 404 - Not Found).

Looking at your code, nothing seems strange, but it is hard to tell when I
can't test it or get an error name/message.

Maybe could you try testing the measuring tool with only one layer and see
if that works. At least that way we can figure out if the problem is the
two layers.

Let me know how it goes

On Thu, Nov 6, 2014 at 5:49 PM, odelphia notifications@github.com wrote:

> hi keyjote - thank you for the feedback.
> 
> Yes, the js and css are all loaded. see this please:
> http://erichsen-group.com/demoland/taylorpeterh/index19.html
> 
> The problem is that the layer toggling does not work. Code snippet below.
> You will see I am calling at least 2 mapbox json layers as overlay on the
> bottom.
> var cloudmadeUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
> http://tile.openstreetmap.org/%7Bz%7D/%7Bx%7D/%7By%7D.png',
> 
> cloudmade = new L.TileLayer(cloudmadeUrl, {maxZoom: 18});
> var main = new L.Map('map', {layers: [cloudmade], center: new L.LatLng(54,
> -0.3), zoom: 6});
> 
> var measuringTool;
> var optionsMeasureLabel = {
> minWidth: 50,
> autoPan: false,
> closeButton: false,
> className: 'measuring-label'
> };
> $('#measuring-tool').click(function() {
> if ($(this).hasClass('active')) {
> $(this).removeClass('active');
> if (measuringTool) {
> measuringTool.disable();
> }
> } else {
> // only 1 option can be active
> $('.btn.btn-primary.active').click();
> $(this).addClass('active');
> if (!measuringTool) {
> measuringTool = new L.MeasuringTool(main);
> }
> measuringTool.enable();
> }
> });
> 
> ```
> main.layers({
>        1: { api: 'http://a.tiles.mapbox.com/v3/inosys.1cpsycqc.jsonp',
>           center: {  ease: 1000 }
>           },
> 
>      2: {
>         api: 'http://a.tiles.mapbox.com/v3/mapster88.1.jsonp',
>            center: {  ease: 1000 }
>      },
> ```
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kartena/Leaflet.EditableHandlers/issues/10#issuecomment-62010573
> .

## 

Daniel

**Comment by odelphia** [comment]
Thank you. I got it working. I was applying both js calls for mapbox and leaflet. Thanks again for providing the tool – its very nice!

C

**Comment by keyjote** [comment]
glad you got it working 
have a good one
