### ISSUE TITLE
Custom Distance for the Measuring Tool

### ISSUE THREAD

**Issue by skunkfu2** [kartena/Leaflet.EditableHandlers#3]
Hey,

I realise this plugin has not been updated in a while, but I hope I can ask a question.

I am using Leaflet for a game map and wondering if there is there any way of defining a custom distance?

The map I am using is 2km x 2km.

Hope to hear from anybody!

Thank you.

**Comment by seabre** [comment]
Custom distance, as in, showing a different unit than meters?

**Comment by skunkfu2** [comment]
Hey seabre, 

Not all, I still wish to use meters. Sorry if I didn't describe it properly.

I am using a game map with custom tiles and the maximum distance between each side of the map is 2km.

When using the measuring tool, I measure from point A to point B, and it gives me a crazy distance of 10231840.88m.

How would I go about defining the maximum distance between each end of the map? So instead of such a large distance, it will give me, for example, 200m.

Also, I tried using crs: L.CRS.Simple for simple latlng (which I use already for the map) however this does not work and it throws the following error: "Uncaught TypeError: Cannot call method 'latLngToPoint' of undefined".

I know I'm shocking at describing things, so I'll be happy to do a jsfiddle if need Be.

Cheers.

**Comment by perliedman** [comment]
The measuring tool uses Leaflet's L.LatLng.distanceTo to calculate the distance between to LatLngs. In your case, since you're not using real latitudes and longitudes (I guess?), this method will give bogus values back.

A hack you could try is to overwrite L.LatLng.prototype.distanceTo with whatever distance calculation that suites you (I guess it would be an application of the Pythagorean theorem).

It could be nice to add functionality to the measuring tool so that you could give it your own function for calculating distances.

**Comment by skunkfu2** [comment]
Hey perliedman,

Thanks for pointing me to the distanceTo function. My Javascript skills are limited but I will see what I can come up with.

Cheers buddy.
